"""
Convert 64x64 test images to MoonBit byte array test code.
"""
import os

TEST_DIR = "d:/moonbit-image/test_images"
OUT_FILE = "d:/moonbit-image/medium_image_test.mbt"

images_to_embed = [
    ("bmp_64x64.bmp", "decode_bmp"),
    ("tga_64x64.tga", "decode_tga"),
    ("png_64x64.png", "decode_png"),
    ("png_rgba_64x64.png", "decode_png"),
    ("qoi_64x64.qoi", "decode_qoi"),
]

expected_formats = {
    "bmp_64x64.bmp": "RGB8",
    "tga_64x64.tga": "RGBA8",   # TGA decoder always outputs RGBA8
    "png_64x64.png": "RGB8",
    "png_rgba_64x64.png": "RGBA8",
    "qoi_64x64.qoi": "RGBA8",   # QOI decoder always outputs RGBA8
}

# Known-good checksums from PIL verification
check_sums = {
    # For 64x64: sum of all R, G, B values
    # R = (x*7)%256, G = (y*13)%256, B = ((x+y)*11)%256
    # 64x64 image: sum_x(0..63) of (x*7)%256 = ?
}

def compute_checksums(w, h):
    """Compute expected pixel checksums for the test pattern."""
    sum_r, sum_g, sum_b = 0, 0, 0
    for y in range(h):
        for x in range(w):
            sum_r += (x * 7) % 256
            sum_g += (y * 13) % 256
            sum_b += ((x + y) * 11) % 256
    return sum_r, sum_g, sum_b

# Compute expected checksums
sum_r_64, sum_g_64, sum_b_64 = compute_checksums(64, 64)

def bytes_to_mbt_array(data, indent=4):
    """Convert bytes to MoonBit byte array syntax."""
    prefix = " " * indent
    lines = []
    chunk_size = 16
    for i in range(0, len(data), chunk_size):
        chunk = data[i:i+chunk_size]
        hex_vals = ", ".join(f"0x{b:02X}" for b in chunk)
        lines.append(f"{prefix}{hex_vals},")
    return "\n".join(lines)

# Generate the test file
lines = []
lines.append('// Medium-sized image tests (64x64) - Auto-generated by test_medium_images.py')
lines.append('')
lines.append('// Expected checksums for 64x64 test pattern:')
lines.append(f'//   R=(x*7)%256, G=(y*13)%256, B=((x+y)*11)%256')
lines.append(f'//   sum_r={sum_r_64}, sum_g={sum_g_64}, sum_b={sum_b_64}')
lines.append('')
lines.append('// Helper: compute pixel checksum for verification')
lines.append('fn compute_checksum(img : Image) -> (Int, Int, Int) {')
lines.append('  let mut sum_r = 0')
lines.append('  let mut sum_g = 0')
lines.append('  let mut sum_b = 0')
lines.append('  for y = 0; y < img.height; y = y + 1 {')
lines.append('    for x = 0; x < img.width; x = x + 1 {')
lines.append('      let c = img.get_pixel(x, y)')
lines.append('      sum_r = sum_r + c.r')
lines.append('      sum_g = sum_g + c.g')
lines.append('      sum_b = sum_b + c.b')
lines.append('    }')
lines.append('  }')
lines.append('  (sum_r, sum_g, sum_b)')
lines.append('}')
lines.append('')

for filename, decoder_fn in images_to_embed:
    filepath = os.path.join(TEST_DIR, filename)
    with open(filepath, "rb") as f:
        data = f.read()

    var_name = filename.replace(".", "_").replace("64x64", "64")
    expected_format = expected_formats[filename]
    size_kb = len(data) / 1024

    lines.append(f'// {"-"*70}')
    lines.append(f'// Test: {filename} ({size_kb:.1f} KB) -> {decoder_fn}() -> {expected_format}')
    lines.append(f'// {"-"*70}')
    lines.append('')
    lines.append(f'fn make_{var_name}() -> Bytes {{')
    lines.append('  make_bytes([')
    lines.append(bytes_to_mbt_array(data))
    lines.append('  ])')
    lines.append('}')
    lines.append('')

    test_name = filename.replace(".", "_").replace("64x64", "64")
    lines.append(f'test "medium_{test_name}" {{')
    lines.append(f'  let img = {decoder_fn}(make_{var_name}())')
    lines.append(f'  check_dims(img, 64, 64)')
    if expected_format == "RGB8":
        lines.append(f'  match img.format {{')
        lines.append(f'    PixelFormat::RGB8 => ()')
        lines.append(f'    _ => raise Failure::Failure("Expected RGB8 format")')
        lines.append(f'  }}')
    elif expected_format == "RGBA8":
        lines.append(f'  match img.format {{')
        lines.append(f'    PixelFormat::RGBA8 => ()')
        lines.append(f'    _ => raise Failure::Failure("Expected RGBA8 format")')
        lines.append(f'  }}')

    # Verify corner pixels
    lines.append(f'  // Verify corner pixels')
    lines.append(f'  check_pixel(img, 0, 0, {(0*7)%256}, {(0*13)%256}, {((0+0)*11)%256}, 255)')
    lines.append(f'  check_pixel(img, 63, 0, {(63*7)%256}, {(0*13)%256}, {((63+0)*11)%256}, 255)')
    lines.append(f'  check_pixel(img, 0, 63, {(0*7)%256}, {(63*13)%256}, {((0+63)*11)%256}, 255)')
    lines.append(f'  check_pixel(img, 63, 63, {(63*7)%256}, {(63*13)%256}, {((63+63)*11)%256}, 255)')
    lines.append(f'  check_pixel(img, 32, 32, {(32*7)%256}, {(32*13)%256}, {((32+32)*11)%256}, 255)')

    # Full checksum verification
    lines.append(f'  // Full checksum verification (sum of all R,G,B values)')
    lines.append(f'  let (sr, sg, sb) = compute_checksum(img)')
    lines.append(f'  if sr != {sum_r_64} {{')
    lines.append(f'    raise Failure::Failure("R-checksum mismatch: got " + sr.to_string() + ", expected {sum_r_64}")')
    lines.append(f'  }}')
    lines.append(f'  if sg != {sum_g_64} {{')
    lines.append(f'    raise Failure::Failure("G-checksum mismatch: got " + sg.to_string() + ", expected {sum_g_64}")')
    lines.append(f'  }}')
    lines.append(f'  if sb != {sum_b_64} {{')
    lines.append(f'    raise Failure::Failure("B-checksum mismatch: got " + sb.to_string() + ", expected {sum_b_64}")')
    lines.append(f'  }}')
    lines.append(f'  println("Medium {filename} test passed!")')
    lines.append(f'}}')
    lines.append('')

with open(OUT_FILE, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print(f"Generated {OUT_FILE}")
print(f"Expected checksums: sum_r={sum_r_64}, sum_g={sum_g_64}, sum_b={sum_b_64}")
print(f"Files embedded: {len(images_to_embed)}")
for name, _ in images_to_embed:
    filepath = os.path.join(TEST_DIR, name)
    size_kb = os.path.getsize(filepath) / 1024
    print(f"  {name}: {size_kb:.1f} KB")
