#!/usr/bin/env python3
"""Generate MoonBit test file with checksum verification for real 4K photos."""

import os
from PIL import Image as PILImage

photos_dir = 'test_images/real_photo'
output_mbt = 'real_photo_test.mbt'

# Get unique base names
photo_bases = set()
for f in os.listdir(photos_dir):
    if '_bmp.bmp' in f:
        photo_bases.add(f.rsplit('_bmp.bmp', 1)[0])

photo_bases = sorted(photo_bases)
print(f'Found {len(photo_bases)} unique photos')

# Read original PNG reference checksums
photo_refs = {}
for base in photo_bases:
    orig_path = os.path.join(photos_dir, f'{base}_original.png')
    if not os.path.exists(orig_path):
        orig_path = os.path.join(photos_dir, f'{base}.png')
    if not os.path.exists(orig_path):
        continue
    try:
        img = PILImage.open(orig_path).convert('RGB')
        pixels = list(img.getdata())
        r_sum = sum(p[0] for p in pixels)
        g_sum = sum(p[1] for p in pixels)
        b_sum = sum(p[2] for p in pixels)
        photo_refs[base] = {
            'width': img.size[0],
            'height': img.size[1],
            'r_sum': r_sum,
            'g_sum': g_sum,
            'b_sum': b_sum,
        }
        print(f'{base}: {img.size[0]}x{img.size[1]} R={r_sum} G={g_sum} B={b_sum}')
    except Exception as e:
        print(f'  Error reading {orig_path}: {e}')


def read_jpg_checksums(jpg_path):
    """Read JPEG and compute actual checksums (different from lossless PNG reference)."""
    img = PILImage.open(jpg_path).convert('RGB')
    pixels = list(img.getdata())
    return (sum(p[0] for p in pixels),
            sum(p[1] for p in pixels),
            sum(p[2] for p in pixels))


def write_hex_array(binary_data):
    """Format binary data as MoonBit make_bytes array literal."""
    lines = []
    for i in range(0, len(binary_data), 20):
        chunk = binary_data[i:i+20]
        lines.append('    ' + ', '.join(f'0x{b:02X}' for b in chunk) + ',')
    return '[\n' + '\n'.join(lines) + '\n  ]'


with open(output_mbt, 'w', encoding='utf-8') as f:
    f.write("""// Real 4K Photo Decoding Tests
// Auto-generated by Python pipeline. Verifies channel sums match PIL reference.
//
// Each test decodes a 4K photo and compares R/G/B channel sums
// against the PIL reference decoder output.

""")

    for base in sorted(photo_refs.keys()):
        ref = photo_refs[base]
        w, h = ref['width'], ref['height']
        r_sum, g_sum, b_sum = ref['r_sum'], ref['g_sum'], ref['b_sum']

        # Determine available formats for this photo
        formats_to_test = []

        # Lossless formats (use PNG reference checksums)
        for fmt_tag, ext in [('bmp', '.bmp'), ('png', '.png'), ('tga', '.tga')]:
            filepath = os.path.join(photos_dir, f'{base}_{fmt_tag}{ext}')
            if os.path.exists(filepath):
                formats_to_test.append((fmt_tag, filepath, r_sum, g_sum, b_sum, False))

        # JPEG is lossy - compute actual JPEG reference values
        jpg_path = os.path.join(photos_dir, f'{base}_jpeg.jpg')
        if os.path.exists(jpg_path):
            jpg_r, jpg_g, jpg_b = read_jpg_checksums(jpg_path)
            formats_to_test.append(('jpeg', jpg_path, jpg_r, jpg_g, jpg_b, True))

        for fmt_tag, filepath, exp_r, exp_g, exp_b, is_lossy in formats_to_test:
            with open(filepath, 'rb') as bf:
                binary = bf.read()

            safe_name = f'{base}_{fmt_tag}'
            test_name = f'real_{safe_name}'
            hex_str = write_hex_array(binary)

            if is_lossy:
                check_code = f"""  // JPEG lossy: allow +-2 tolerance per channel
  let d_r = if act_r > ref_r {{ act_r - ref_r }} else {{ ref_r - act_r }}
  let d_g = if act_g > ref_g {{ act_g - ref_g }} else {{ ref_g - act_g }}
  let d_b = if act_b > ref_b {{ act_b - ref_b }} else {{ ref_b - act_b }}
  if d_r > 2 || d_g > 2 || d_b > 2 """
            else:
                check_code = """  if act_r != ref_r || act_g != ref_g || act_b != ref_b """

            check_code += """ {{
    raise Failure::Failure(
      "Channel sum mismatch: R(" + act_r.to_string() + " vs " + ref_r.to_string() +
      ") G(" + act_g.to_string() + " vs " + ref_g.to_string() +
      ") B(" + act_b.to_string() + " vs " + ref_b.to_string() + ")"
    )
  }}"""

            f.write(f"""test "{test_name}" {{
  let data = make_bytes({hex_str})
  let img = @image.decode(data)
  if img.width != {w} || img.height != {h} {{
    raise Failure::Failure("Size mismatch: expect {w}x{h}")
  }}

  // Edge pixel access
  let _p00 = img.get_pixel(0, 0)
  let _p11 = img.get_pixel({w - 1}, {h - 1})

  // Compute full channel sums via to_rgba8()
  let ref_r : Int = {exp_r}
  let ref_g : Int = {exp_g}
  let ref_b : Int = {exp_b}
  let rgb = img.to_rgba8()
  let mut act_r = 0
  let mut act_g = 0
  let mut act_b = 0
  let n = rgb.width * rgb.height
  for i = 0; i < n; i = i + 1 {{
    act_r = act_r + rgb.data[i * 4].to_int()
    act_g = act_g + rgb.data[i * 4 + 1].to_int()
    act_b = act_b + rgb.data[i * 4 + 2].to_int()
  }}

{check_code}
}}

""")

    f.write('\n// End auto-generated test file\n')

total_size_mb = os.path.getsize(output_mbt) / (1024 * 1024)
print(f'Generated: {output_mbt} ({total_size_mb:.1f} MB)')
print(f'Total unique photo bases: {len(photo_refs)}')
