name: CI

on:
  push:
    branches: [default, main, master]
  pull_request:
    branches: [default, main, master]

jobs:
  check:
    name: MoonBit CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup MoonBit
        uses: hustcer/setup-moonbit@v1
        with:
          version: latest

      - name: moon check --fmt --deny-warn
        run: moon check --fmt --deny-warn

      - name: moon test
        run: moon test

      - name: moon info && git diff --exit-code
        run: |
          moon info
          git diff --exit-code
