name: CI

on:
  push:
    branches: [default, main, master]
  pull_request:
    branches: [default, main, master]

jobs:
  check:
    name: MoonBit CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup MoonBit
        uses: hustcer/setup-moonbit@v1
        with:
          version: latest

      - name: 1. moon check
        run: moon check --deny-warn

      - name: 2. moon fmt --check
        run: moon fmt --check

      - name: 3. moon info
        run: |
          moon info

      - name: 4. moon test
        run: moon test
